version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@3.2.0

workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          context: AWS
          repo: {{.ECR_REPO}}
          tag: ${CIRCLE_SHA1}
#      - aws-ecs/deploy-service-update:
#          context: AWS
#          cluster: '{{.ECS_CLUSTER}}'
#          container-image-name-updates: 'container={{.APP_NAME}},tag=${CIRCLE_SHA1}'
#          family: '{{.APP_NAME}}'
#          service-name: '{{.SERVICE_NAME}}'
#          requires:
#            - aws-ecr/build-and-push-image
